<a href="https://colab.research.google.com/github/ShivamKum4r/Machine-learning/blob/main/Datacleaning_and_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# data cleaning
import pandas as pd
df = pd.read_csv('olympics.csv')
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,? Summer,01 !,02 !,03 !,Total,? Winter,01 !,02 !,03 !,Total,? Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [2]:
df = pd.read_csv('olympics.csv', index_col = 0, skiprows=1)
df

,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [3]:
df.columns

Index(['? Summer', '01 !', '02 !', '03 !', 'Total', '? Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '? Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [4]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='?':
        df.rename(columns={col:'#' + col[1:]}, inplace=True)

df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [5]:
df['Gold'] > 0 #boolen masking

Afghanistan (AFG)                               False
Algeria (ALG)                                    True
Argentina (ARG)                                  True
Armenia (ARM)                                    True
Australasia (ANZ) [ANZ]                          True
                                                ...
Independent Olympic Participants (IOP) [IOP]    False
Zambia (ZAM) [ZAM]                              False
Zimbabwe (ZIM) [ZIM]                             True
Mixed team (ZZX) [ZZX]                           True
Totals                                           True
Name: Gold, Length: 147, dtype: bool

In [6]:
only_gold = df.where(df['Gold'] > 0)
only_gold.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0

In [7]:
only_gold['Gold'].count()

np.int64(100)

In [8]:
df['Gold'].count()

np.int64(147)

In [9]:
only_gold = only_gold.dropna()
only_gold.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
Australia (AUS) [AUS] [Z],25.0,139.0,152.0,177.0,468.0,18.0,5.0,3.0,4.0,12.0,43.0,144.0,155.0,181.0,480.0

In [10]:
only_gold = df[df['Gold'] > 0]
only_gold.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480

In [11]:
len(df[(df['Gold'] > 0) | (df['Gold.1'] > 0)])

101

In [12]:
df[(df['Gold.1'] > 0) & (df['Gold'] == 0)]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Liechtenstein (LIE),16,0,0,0,0,18,2,2,5,9,34,2,2,5,9

In [13]:
#indexing dataframe
df = df.reset_index()
df = df.set_index('Gold')
df

,index,# Summer,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Gold,,,,,,,,,,,,,,,
0,Afghanistan (AFG),13,0,2,2,0,0,0,0,0,13,0,0,2,2
5,Algeria (ALG),12,2,8,15,3,0,0,0,0,15,5,2,8,15
18,Argentina (ARG),23,24,28,70,18,0,0,0,0,41,18,24,28,70
1,Armenia (ARM),5,2,9,12,6,0,0,0,0,11,1,2,9,12
3,Australasia (ANZ) [ANZ],2,4,5,12,0,0,0,0,0,2,3,4,5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Independent Olympic Participants (IOP) [IOP],1,1,2,3,0,0,0,0,0,1,0,1,2,3
0,Zambia (ZAM) [ZAM],12,1,1,2,0,0,0,0,0,12,0,1,1,2
3,Zimbabwe (ZIM) [ZIM],12,4,1,8,1,0,0,0,0,13,3,4,1,8
8,Mixed team (ZZX) [ZZX],3,5,4,17,0,0,0,0,0,3,8,5,4,17
4809,Totals,27,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [14]:
df = df.reset_index()
df.head()

,Gold,index,# Summer,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,0,Afghanistan (AFG),13,0,2,2,0,0,0,0,0,13,0,0,2,2
1,5,Algeria (ALG),12,2,8,15,3,0,0,0,0,15,5,2,8,15
2,18,Argentina (ARG),23,24,28,70,18,0,0,0,0,41,18,24,28,70
3,1,Armenia (ARM),5,2,9,12,6,0,0,0,0,11,1,2,9,12
4,3,Australasia (ANZ) [ANZ],2,4,5,12,0,0,0,0,0,2,3,4,5,12

In [15]:
df = df.set_index(['Gold', 'Gold.1'])
df.head()

,,index,# Summer,Silver,Bronze,Total,# Winter,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Gold,Gold.1,,,,,,,,,,,,,,
0,0,Afghanistan (AFG),13,0,2,2,0,0,0,0,13,0,0,2,2
5,0,Algeria (ALG),12,2,8,15,3,0,0,0,15,5,2,8,15
18,0,Argentina (ARG),23,24,28,70,18,0,0,0,41,18,24,28,70
1,0,Armenia (ARM),5,2,9,12,6,0,0,0,11,1,2,9,12
3,0,Australasia (ANZ) [ANZ],2,4,5,12,0,0,0,0,2,3,4,5,12

In [17]:
# data cleaning(Missing values)
import pandas as pd
df = pd.read_csv('log.csv')
df

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN
20  1469974754     sue  advanced.html                 30    NaN     NaN
21  1469974824     sue  advanced.html                 31    NaN     NaN
22  1469974854     sue  advanced.html                 32    NaN     NaN
23  1469974924     sue  advanced.html                 33    NaN     NaN
24  1469977424     bob     intro.html                  1   True    10.0
25  1469977454     bob     intro.html                  1    NaN     NaN
26  1469977484     bob     intro.html                  1    NaN     NaN
27  1469977634     bob     intro.html                  1    NaN     NaN
28  1469977664     bob     intro.html                  1    NaN     NaN
29  1469974634  cheryl     intro.html                 12    NaN     NaN
30  1469974664  cheryl     intro.html                 13    NaN     NaN
31  1469977694     bob     intro.html                  1    NaN     NaN
32  1469977724     bob     intro.html                  1    NaN     NaN

In [18]:
df.isnull()

     time   user  video  playback position  paused  volume
0   False  False  False              False   False   False
1   False  False  False              False    True    True
2   False  False  False              False    True    True
3   False  False  False              False    True    True
4   False  False  False              False    True    True
5   False  False  False              False    True    True
6   False  False  False              False    True    True
7   False  False  False              False    True    True
8   False  False  False              False    True    True
9   False  False  False              False    True    True
10  False  False  False              False    True    True
11  False  False  False              False    True    True
12  False  False  False              False    True    True
13  False  False  False              False   False   False
14  False  False  False              False    True    True
15  False  False  False              False    True    True
16  False  False  False              False    True   False
17  False  False  False              False    True    True
18  False  False  False              False    True    True
19  False  False  False              False    True    True
20  False  False  False              False    True    True
21  False  False  False              False    True    True
22  False  False  False              False    True    True
23  False  False  False              False    True    True
24  False  False  False              False   False   False
25  False  False  False              False    True    True
26  False  False  False              False    True    True
27  False  False  False              False    True    True
28  False  False  False              False    True    True
29  False  False  False              False    True    True
30  False  False  False              False    True    True
31  False  False  False              False    True    True
32  False  False  False              False    True    True

In [19]:
df = df.set_index('time')
df

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469977514     bob     intro.html                  1    NaN     NaN
1469977544     bob     intro.html                  1    NaN     NaN
1469977574     bob     intro.html                  1    NaN     NaN
1469977604     bob     intro.html                  1    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974454     sue  advanced.html                 24    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974424     sue  advanced.html                 23  False    10.0
1469974554     sue  advanced.html                 26    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974724     sue  advanced.html                 29    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN
1469974854     sue  advanced.html                 32    NaN     NaN
1469974924     sue  advanced.html                 33    NaN     NaN
1469977424     bob     intro.html                  1   True    10.0
1469977454     bob     intro.html                  1    NaN     NaN
1469977484     bob     intro.html                  1    NaN     NaN
1469977634     bob     intro.html                  1    NaN     NaN
1469977664     bob     intro.html                  1    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974664  cheryl     intro.html                 13    NaN     NaN
1469977694     bob     intro.html                  1    NaN     NaN
1469977724     bob     intro.html                  1    NaN     NaN

In [20]:
df = df.sort_index()
df

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454     sue  advanced.html                 24    NaN     NaN
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974664  cheryl     intro.html                 13    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974724     sue  advanced.html                 29    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN
1469974854     sue  advanced.html                 32    NaN     NaN
1469974924     sue  advanced.html                 33    NaN     NaN
1469977424     bob     intro.html                  1   True    10.0
1469977454     bob     intro.html                  1    NaN     NaN
1469977484     bob     intro.html                  1    NaN     NaN
1469977514     bob     intro.html                  1    NaN     NaN
1469977544     bob     intro.html                  1    NaN     NaN
1469977574     bob     intro.html                  1    NaN     NaN
1469977604     bob     intro.html                  1    NaN     NaN
1469977634     bob     intro.html                  1    NaN     NaN
1469977664     bob     intro.html                  1    NaN     NaN
1469977694     bob     intro.html                  1    NaN     NaN
1469977724     bob     intro.html                  1    NaN     NaN

In [21]:
df1=df.dropna()
df1

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469977424     bob     intro.html                  1   True    10.0

In [25]:
df = df.fillna(method='ffill')
df.head(10)

/tmp/ipython-input-25-739057087.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')

              user          video  playback position  paused  volume
time
1469974424  cheryl     intro.html                  5   False    10.0
1469974424     sue  advanced.html                 23   False    10.0
1469974454     sue  advanced.html                 24   False    10.0
1469974454  cheryl     intro.html                  6   False    10.0
1469974484  cheryl     intro.html                  7   False    10.0
1469974514  cheryl     intro.html                  8   False    10.0
1469974524     sue  advanced.html                 25   False    10.0
1469974544  cheryl     intro.html                  9   False    10.0
1469974554     sue  advanced.html                 26   False    10.0
1469974574  cheryl     intro.html                 10   False    10.0