<a href="https://colab.research.google.com/github/ShivamKum4r/Machine-learning/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
ser1=pd.Series({'Material':'Wooden',
                'Colour':'Maroon',
                'Price': 25000})
ser2=pd.Series({'Material':'Plywood',
                'Colour':'Yellow',
                'Price': 20000})
ser3=pd.Series({'Material':'Plastic',
                'Colour':'Red',
                'Price': 1500})
ser4=pd.Series({'Material':'Stainless Steel',
                'Colour':'Silver',
                'Price': 55000})
ser5=pd.Series({'Material':'Wooden',
                'Colour':'Light Blue',
                'Price': 2500})
ser6=pd.Series({'Material':'Aluminium',
                'Colour':'Golden',
                'Price': 65000})
df=pd.DataFrame([ser1,ser2,ser3,ser4,ser5,ser6],index=['Sofa','Dinning Table','Chair','Sofa','Chair','Dinning Table'])
print(df)
print("\nChair and sofa:")
print(df.loc[['Chair','Sofa']])
print("\nFurniture Details:")
print(df.loc[df['Price']>25000])
print("\nFurniture Details:")
print(df.loc[df['Price']<1000])
print("\nAlternative Rows:")
print(df.iloc[0::2])

                      Material      Colour  Price
Sofa                    Wooden      Maroon  25000
Dinning Table          Plywood      Yellow  20000
Chair                  Plastic         Red   1500
Sofa           Stainless Steel      Silver  55000
Chair                   Wooden  Light Blue   2500
Dinning Table        Aluminium      Golden  65000

Chair and sofa:
              Material      Colour  Price
Chair          Plastic         Red   1500
Chair           Wooden  Light Blue   2500
Sofa            Wooden      Maroon  25000
Sofa   Stainless Steel      Silver  55000

Furniture Details:
                      Material  Colour  Price
Sofa           Stainless Steel  Silver  55000
Dinning Table        Aluminium  Golden  65000

Furniture Details:
Empty DataFrame
Columns: [Material, Colour, Price]
Index: []

Alternative Rows:
      Material      Colour  Price
Sofa    Wooden      Maroon  25000
Chair  Plastic         Red   1500
Chair   Wooden  Light Blue   2500

In [3]:
import pandas as pd

data = {
    'col1': {'row1': 1, 'row2': 2},
    'col2': {'row1': 3, 'row2': 4}
}

df = pd.DataFrame(data)

print(df)

      col1  col2
row1     1     3
row2     2     4

In [5]:
import pandas as pd
brics=pd.read_csv('brics.csv',index_col=0)
print(brics)
print("\n",brics.describe())
print("\n\n",brics["country"])
brics['on_earth']='True'
print("\n\n",brics)
brics["density"]=brics["population"]/brics["area"]*1000000
print("\n\n",brics)
print("\n\n",brics.iloc[1:3])
print("\n\n",brics.iloc[1:3,0:2])
print("\n",brics["capital"].loc["CH"])
print("\n",brics.loc["CH"]["capital"])
print("\n",brics.loc["CH","capital"])

         country  population      area    capital
BR        Brazil         200   8515767   Brasilia
RU        Russia         144  17098242     Moscow
IN         India        1252   3287590  New Delhi
CH         China        1357   9596961    Beijing
SA  South Africa          55   1221037   Pretoria

         population          area
count     5.000000  5.000000e+00
mean    601.600000  7.943919e+06
std     644.806405  6.199591e+06
min      55.000000  1.221037e+06
25%     144.000000  3.287590e+06
50%     200.000000  8.515767e+06
75%    1252.000000  9.596961e+06
max    1357.000000  1.709824e+07


 BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object


          country  population      area    capital on_earth
BR        Brazil         200   8515767   Brasilia     True
RU        Russia         144  17098242     Moscow     True
IN         India        1252   3287590  New Delhi     True
CH         China        1357   9596961    Beijing     True
SA  South Africa          55   1221037   Pretoria     True


          country  population      area    capital on_earth     density
BR        Brazil         200   8515767   Brasilia     True   23.485847
RU        Russia         144  17098242     Moscow     True    8.421918
IN         India        1252   3287590  New Delhi     True  380.826076
CH         China        1357   9596961    Beijing     True  141.398928
SA  South Africa          55   1221037   Pretoria     True   45.043680


    country  population      area    capital on_earth     density
RU  Russia         144  17098242     Moscow     True    8.421918
IN   India        1252   3287590  New Delhi     True  380.826076


    country  population
RU  Russia         144
IN   India        1252

 Beijing

 Beijing

 Beijing

In [7]:
import pandas as pd
#census=pd.read_csv('census.csv')
#print(census)
census_df=pd.read_csv('census.csv')
#print(census_df.groupby('STATE')['COUNTY'].count())
x=census_df.groupby('STNAME').count()['SUMLEV']
ans=x.idxmax()
print(ans)

Georgia

In [ ]:
import pandas as pd
census_df=pd.read_csv('census.csv')
#x=census_df.groupby('COUNTY')['CENSUS2010POP'].nlargest(3)
x_df=census_df.sort_values(by=['STNAME','CENSUS2010POP'],ascending=False).groupby('STNAME').head(3)
ans=x_df.groupby('STNAME').sum().sort_values(by='CENSUS2010POP',).head(3).index.tolist()
print(ans)

['Wyoming', 'Vermont', 'North Dakota']

In [9]:
import pandas as pd
df=pd.read_csv('olympics.csv')
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,? Summer,01 !,02 !,03 !,Total,? Winter,01 !,02 !,03 !,Total,? Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [10]:
df=pd.read_csv('olympics.csv',index_col=0,skiprows=1)
df

,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [11]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+ col[4:]},inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+ col[4:]},inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+ col[4:]},inplace=True)
    if col[:1]=='?':
        df.rename(columns={col:'#'+ col[1:]},inplace=True)
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12